apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  labels:
    app: mediawiki
spec:
  ports:
    - port: 80
  selector:
    app: mediawiki
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-pv
  labels:
    app: mediawiki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mediawiki
  labels:
    app: mediawiki
spec:
  selector:
    matchLabels:
      app: mediawiki
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mediawiki
        tier: frontend
      annotations:
        backup.velero.io/backup-volumes: mediawiki-persistent-storage
    spec:
      containers:
      - image: mediawiki
        name: mediawiki
        ports:
        - containerPort: 80
          name: mediawiki
        volumeMounts:
        - name: mediawiki-persistent-storage
          mountPath: /var/www/html/images
        securityContext:
          privileged: true
      volumes:
      - name: mediawiki-persistent-storage
        persistentVolumeClaim:
          claimName: mediawiki-pv
      initContainers:
      - name: install
        image: busybox
        volumeMounts:
        - name: mediawiki-persistent-storage
          mountPath: /var/www/html/images
        command:
        - wget
        - "-O"
        - "/var/www/html/LocalSettings.php"
        - https://raw.githubusercontent.com/sunnypatel7/Mediawiki-Kubernetes/master/LocalSettings.php
      
          

